### ISSUE TITLE
Must restart Multitouch after wake from sleep

### ISSUE THREAD

**Issue by ab1470** [Brass-Monkery/Multitouch-Bugs#35] opened 2018-12-08 00:15 UTC
Every time I wake my computer from sleep, I need to restart Multitouch in order to get it to work.

**Comment by rxhanson** [comment] 2018-12-08 11:39
Is this something new that just started happening, or has this always been the case for you?

**Comment by rxhanson** [comment] 2018-12-08 11:44
Also, there are different levels of sleep. Is this after being asleep only for a long time, like over night, or for less time?

**Comment by ab1470** [comment] 2018-12-08 21:00
I believe this started with 1.8.1. It happens after all forms of sleep, including when my screen goes blank after a few minutes of inactivity.

**Comment by rxhanson** [comment] 2018-12-08 21:55
I did make some changes in v1.8 that could have affected this. It could be something where macOS is changing device identifiers when waking from sleep and Multitouch doesn't currently reassess the identifiers at that time to know if any are no longer applicable. I can make a few changes to see if that's the case, but it's a little bit of a stab in the dark since I can't reproduce it on my end. 

I had actually experienced a similar thing prior to Multitouch v1.0 on my old MacBook Air that wasn't related to device identifiers - it was just that macOS was not sending touch data after waking from sleep. Nobody ever reported it though, and it was _only_ on that Mac so it could be something specific to certain macs.

Hopefully this was in fact related to changes I made in v1.8, and I can build in some sort of fix around that. If not, it'll most likely require a debug build so that we can know what's actually going on.

**Comment by ab1470** [comment] 2018-12-09 02:16
Perhaps this is a clue as to what might be happening: under the same conditions that Multitouch stops working (i.e., after my Mac sleeps long enough that the lock screen appears), some (though not all) of the default MacOS trackpad gestures also stop working. Pinch to zoom in/out stops working, as does two-finger swipe from right to open notification center.

The only way I can re-activate the disabled gestures is to go into the MacOS trackpad pref pane, deactivate one of the non-working gestures, and reactivate it.

**Comment by rxhanson** [comment] 2018-12-09 11:51
Thanks for the additional info. Here's a thread on macrumours where people are having similar issues, even without any gesture apps installed: https://forums.macrumors.com/threads/macbook-pro-2018-multitouch-gestures-on-mojave-intermittently-going-out.2136385/

If you don't mind, it would be nice to see if somehow Multitouch is causing these issues with the built-in gestures. Try disabling launch on login on Multitouch, closing it, then logging out and logging in (or restarting your mac). If you're still having the issues, then at least we know the root of it is in Apple's hands and may be fixed altogether by Apple at some point. Knowing whether or not it's Apple's problems doesn't change the fact that I'll have to build in some kind of fix on Multitouch's side, but it's good to know in case I can rip out any fix Multitouch side in the future. The Multitouch side fix could end up being an automatic restart of the app when touches are not being recognized (kind of ugly).

I'm thinking that this is not directly related to the changes that I put into v1.8, although there's a bit of robustness I can improve there based on things I've learned since. Although I could be wrong, this appears to to be one of those issues that only affects a handful of users - making you a lucky one :)

In order to implement the automatic restart or reinitialization of the app when touches are not sent to Multitouch, I'll have to determine that touches are existing but are not making it to Multitouch. This could take a few tries to get right, and probably some debug builds. I'll post an update when I have one available for download.

**Comment by rxhanson** [comment] 2018-12-09 11:53
Also, I appreciate that you've taken the time to investigate this, because I know how annoying it is to try to troubleshoot sleep/wake issues.

**Comment by ab1470** [comment] 2018-12-09 22:00
I haven't taken the exact steps that you've spelled out yet, but I just observed something interesting as I tried to reproduce the problem:

- I started out with my computer is working normally (i.e., with the Multitouch app and all native MacOS gestures functioning as expected), then left the computer idle for long enough that the display went to sleep for about one minute (no lock screen). 
- After waking up the display, all MacOS native gestures worked properly, but the Multitouch app wasn't functioning.
- Next, I quit Multitouch from the menubar icon. Immediately after quitting, some MacOS native gestures (pinch zoom and notification center swipe) stopped working completely. 
- Now I restart Multitouch, and it works as expected. Native pinch zoom and notification center swipe still don't work.
- Finally, I get the native gestures working again by going into the trackpad prefpane, then deselect/reselect the pinch zoom option.

**Comment by rxhanson** [comment] 2018-12-09 22:53
That's some pretty strange behavior. It's interesting that Multitouch would have an impact on the built-in gestures since all it does is listen to the touch data. 

If you don't mind pushing this a little further, would you mind checking the box for "Avoid private frameworks" in the settings and disconnecting any Magic Mouses that you have connected? The reason why I went with the private framework in the first place was because it appeared to fix this type of issue in for other users previously, but maybe it will have the reverse impact for you. 

Hopefully putting in the code to restart or reinitialize Multitouch will keep the built-in gestures working, but it's doubtful that it would be the case provided the behavior you just noted. I'll also take a look at unregistering all of Multitouch's listeners on sleep. I'm guessing that JiTouch or BTT would produce similar behavior?

**Comment by ab1470** [comment] 2018-12-09 23:50
I'll continue to monitor this, of course, but initially it appears that checking "Avoid private frameworks" has solved the issue!

**Comment by rxhanson** [comment] 2018-12-10 12:21
This is confusing behavior from macOS to say the least, but if that works out well for you then that's great. 

By avoiding private frameworks, this means that Multitouch is using an Event Tap and receiving touch data from Apple's "supported" way. Where the private framework was giving us _raw_ touch data, the touch data coming from the Event Tap is after some processing by Apple software - meaning you'll notice differences in Apple's resting touch rejection algorithms and mine. 

Also note that if you do use a Magic Mouse, it will use the private framework regardless of that setting because there's no other way to get touch data for the Magic Mouse.

There's already some logic in place on the Event Tap to restart Multitouch when touch data is empty upon wake, but I'll have to add that type of logic in to the Private Framework side as well. 

If "avoid private frameworks" indeed works out for you, it puts Multitouch in kind of a weird place because some users experienced these issues only with the Event Tap, and you've experienced it only with the private framework. As in, there's not really a simple way to guarantee it will work out of the box for everyone due to flakiness in macOS. Anyways, keep me posted on if you experience any further issues like this.

**Closed** 2019-01-31 16:36 UTC
Labels: bug
