### ISSUE TITLE
Don't Work with Mojave

### ISSUE THREAD

**Issue by silverstroom** [Brass-Monkery/Multitouch-Bugs#17] opened 2018-09-25 10:58 UTC
I've just installed macOS Mojave and the app "multitouch" don't work fine cause it crash at first start

**Comment by rrhanson** [comment] 2018-09-25 11:39
Please email me a crash report to support@multitouch.app so I can quickly figure out the cause of the crash. You can find the crash report by doing the following:
1. Open the "Console" app.
2. Click User Reports on the left. The crash report for Multitouch should be seen here.
3. Right click on the .crash file to find it in Finder.

**Comment by silverstroom** [comment] 2018-09-25 12:57
Hi,

The problem is that there isn’t a crash of the app because it doesn’t run. 
If I push on the app it doesn’t work

**Comment by rodrigoreyes79** [comment] 2018-09-25 16:18
In my case, I am trying to bind a keyboard shortcut (F13) to the 4 finger click gesture. It is not working.

**Comment by rrhanson** [comment] 2018-09-25 19:01
@silverstroom 
Multitouch works fine for me in Mojave, so I'll be depending on you to help get it working on your machine. Did you take a look in "Console" and see if any crash reports were produced? Sometimes an app might appear to not do anything but it may have just crashed before anything happened. If it is failing to start and not producing a crash log, then hopefully there is at least some kind of error message being logged to Console. To narrow it down, please perform the following:
1. Ensure that Multitouch is, in fact, not running by checking in Activity Monitor.
2. Open the "Console" app
3. Click "Errors and Faults" 
4. Add the word "multitouch" to the search bar
5. Attempt to open Multitouch.

If we're still not seeing anything, then I can build a custom version of the app with more logging and send it your way.

Beyond that, another thing you can try is to remove any Multitouch preferences that you have set and try to run it again. First, let's grab your preferences with the following command in Terminal:
`defaults read com.brassmonkery.Multitouch`
Copy the output there and we can use it to restore your settings later. If there is a specific preference causing the problem, then I can narrow it down based on what you had configured, too.
After saving your preferences, delete them with the following command:
`defaults delete com.brassmonkery.Multitouch`
Then attempt to start Multitouch again. If it works now, please send me what your config used to be.

Sorry that things aren't working! Hopefully we can get it working soon. I'll be putting out an update that includes dark mode soon.

**Comment by rrhanson** [comment] 2018-09-25 19:47
@rodrigoreyes79 
Can you file a separate issue for this? I would do it, but it's hard to link it back to you if I do it. 

I'm actually not able to reproduce your issue in a plain vanilla way, so I'll need to ask a few questions for clarification. 
1. Is this a change from behavior before Mojave, or is this just something that you've tried after upgrading to Mojave?
2. Are you using a keyboard with physical F13 keys, or are you mapping usage of F13 through another tool, such as Karabiner? When testing things out with Karabiner, it appears to not detect keyboard input that has been generated by Multitouch. I don't use Karabiner, so I'm not familiar with how things have worked in the past or currently work with it. 

I'm guessing that the gesture is registering properly, but the F13 keystroke is not making its way to your expected endpoint. You can try connecting the gesture to another action, and make sure that works so that we can narrow it down.

Let me know and I'll see what I can do to have it work properly for you.

**Comment by silverstroom** [comment] 2018-09-25 20:11
Thanks for the answer  !!!

So I have tried to reset the preferences and the app start it ! 
But there is a problem; if I put a new shortcut into the settings, it crashes. There isn’t any crash file into the console.app

Salvo Bilotti 

Follow me on LinkdIn ⇩
bit.ly/SalvoBilottiLinkedIn

> Il giorno 25 set 2018, alle ore 9:01 PM, Ryan Hanson <notifications@github.com> ha scritto:
> 
> defaults delete com.brassmonkery.Multitouch

**Comment by rrhanson** [comment] 2018-09-25 21:00
@silverstroom 
Ok, that's really good for narrowing it down. Specifically, what is the shortcut that you are attempting to add when the crash occurs?

**Comment by rrhanson** [comment] 2018-09-26 00:57
@silverstroom 
I think I have it figured out. As you may know, one of the changes in Mojave is increased security restrictions. Due to this, Multitouch fails to initialize if it is not enabled as an "Accessibility Application". 
You'll have to go to System Preferences -> Security & Privacy -> Accessibility (on the left). 
Then add and enable Multitouch to the list.

In my next update for Mojave I will have to force users to do this in order to use Multitouch :(

Let me know if this fixes your issue.

@rodrigoreyes79 
I'm not sure if you are also experiencing a crash when trying to configure the keyboard shortcut, but feel free to create the new issue if that's not what you're seeing.

**Comment by rodrigoreyes79** [comment] 2018-09-26 02:05
@rrhanson I just created a separate bug on https://github.com/Brass-Monkery/Multitouch-Bugs/issues/18

**Comment by rrhanson** [comment] 2018-09-27 01:47
@silverstroom thanks for helping me troubleshoot! Closing this one out.

**Closed by rrhanson** 2018-09-27 01:47 UTC
Labels: bug
