### ISSUE TITLE
Add "fix + swipe" gesture

### ISSUE THREAD

**Issue by ab1470** [Brass-Monkery/Multitouch-Bugs#24] opened 2018-10-24 20:04 UTC
For example, the user can fix their index finger in place, and swipe down using the next two fingers. It sounds kind of unnatural but it works quite well!

**Comment by lorenzofanchi** [comment] 2018-11-05 22:02
This would indeed be great! This is the only reason I'm still using Jitouch at the moment!

Left fixed, slide two down for 'Close tab'
Right fixed, slide two up for 'Open Recently Closed Tab'

**Comment by rxhanson** [comment] 2018-11-06 20:31
I tried the "one finger fixed, slide two down" out on jiTouch and actually had a really hard time getting it to work properly. It also caused the Apple three finger swipe down (windows in current app view) to be executed. I had decided not to implement this one originally because it was too close to the three finger swipe up / down built in Apple gestures, and I'd prefer to avoid getting too close to Apple's gestures. 

I was actually planning on adding the one finger fixed swipe up/down with one finger gestures a while ago, but other features had gotten in the way. @ab1470, @lorenzofanchi, are there any reasons you would prefer the "fix one swipe two" over "fix one swipe one"?

**Comment by lorenzofanchi** [comment] 2018-11-06 22:44
I never had any issues with the gesture myself, but can imagine you'd like to avoid unintended behavior. I'd be fine with the one finger swipe too!

**Comment by rxhanson** [comment] 2018-11-12 21:16
Just a heads up, I've started working on this one and plan to have it in the next release.

**Comment by lorenzofanchi** [comment] 2018-11-25 22:04
Thanks for implementing this!

The swipe down gesture works great, but the swipe up one is very hard to trigger for me... I think it's because the 'swipe finger' movement has to start far below the 'fixed finger' movement. Maybe you can make the starting position for the 'swipe finger' be next to the 'fixed finger'?

**Comment by rxhanson** [comment] 2018-11-26 08:46
@lorenzofanchi thanks for trying this out and giving me feedback so quickly! There’s actually no starting position for the swipe, it is just harder to reach the same velocity going up as it is on the down swipe. I’ll make some slight changes to the up velocity and add a hidden configuration to allow this to be user modified. I’ll post back to this thread when I have the update ready.

**Comment by rxhanson** [comment] 2018-11-26 21:44
@lorenzofanchi 
I've released v1.8.1 that should make the swipe up much easier to execute. It can be updated to from within the app or downloaded from https://multitouch.app/versions. 
I realized in testing this out on other trackpads, that unfortunately not all trackpads report velocities in a consistent manner. This was part of the reason that you experienced the difficulty in executing the swipe up. Unfortunately, this makes configuration much more complicated as it would have to include multiple thresholds for each type of trackpad (magic trackpad 1, 2, and internal trackpads). So I didn't include a hidden config for this in v.1.8.1. 

Let me know if v1.8.1 works for you. If needed, I'll prioritize adding in a way to configure the thresholds manually to let you better tweak when the swipe will actually execute the action.

**Comment by lorenzofanchi** [comment] 2018-11-26 21:54
Just tested it. Unfortunately, the swipe gestures stopped working altogether now (up and down). One fixed and tap still work. Tried removing and re-adding swipe gestures, but no dice...

**Comment by rxhanson** [comment] 2018-11-26 22:11
Thanks for trying this out so quick, I really appreciate it. I'll add in some configuration so that you can adjust the thresholds and we can get something working, but I won't be able to get to it until tomorrow at the earliest.

I think this might be one of those things that boils down to all trackpads just being different and that it is difficult to build a generic case that handles them all. This could be similar to the issues I saw with JiTouch's fix one swipe two that you didn't experience. It's something that I never really would have thought about until having a lot of users with really varying experiences using Multitouch. On one hand, it's rather surprising since it's all Apple hardware, but on the other hand, that's kind of the way things go when dealing directly with hardware. Anyways, thanks again for your prompt help on this! I'll let you know when an update is out.

**Comment by lorenzofanchi** [comment] 2018-11-27 22:08
@rxhanson, Thanks for looking into this at such short notice! I played around with the settings a bit and the following seems to work well:

- Up threshold: 1.5
- Down thershold: 1.6

Also, I wrote a small script to help with testing configs quickly, see below.

```
osascript -e 'quit app "MultiTouch"'

defaults write com.brassmonkery.Multitouch swipeUpVelocityThreshold -float 1.5
defaults write com.brassmonkery.Multitouch swipeDownVelocityThreshold -float 1.6

sleep 1s

open -a MultiTouch
```

**Comment by rxhanson** [comment] 2018-11-28 19:04
@lorenzofanchi, This is great! Thanks for trying this out super quick and providing feedback.

Good idea on the segmented button approach, I think I'll give that a go. 

When I incorporate your thresholds into the next release as one of those sensitivity settings, there is one thing to note: There will be a very minor discrepancy between the release and what you have now with those settings, but hopefully it will feel more natural. My algorithm does a little bit of "smoothing" using two thresholds, a raw velocity threshold and a rolling average velocity threshold. What that means is that I will most likely bump up the raw velocity threshold slightly and add in a lower rolling average velocity threshold. In my tests, this felt better and was worth it, but it might not be noticeable, especially since there seem to be oddly dramatic differences between my 15" 2016 MBP and your 15" 2017 MBP. At any rate, you can definitely let me know if it still feels off after the next release. I'll probably still leave in some type of hidden config to allow overriding the sensitivity settings that I will provide.

Thanks for the help on this. I'll post again when a new release is ready.

**Comment by rxhanson** [comment] 2018-12-03 14:08
@lorenzofanchi, I decided to rewrite the algorithm for the "rest one swipe one" gestures, primarily to just be more consistent across trackpads. Since it's a different algorithm, you'll have to try it out and let me know if it seems off since I couldn't reuse any of your tested values directly. 

I did add in the segmented control, so you can try out the "easy, med, or hard" settings - hopefully one of those works for you. 

Via user defaults again, you can provide more granular settings than just easy, med, or hard. 

The numbers are arbitrary, but the range is from 0.5 to 3.5 in 0.5 increments. "1, 2, and 3" are "easy, med, hard", respectively. The following command would set it between medium and hard:

`defaults write com.brassmonkery.Multitouch swipeDifficulty -float 2.5`

Thanks for working through this with me, as getting the gestures right is almost always a very iterative process since everyone has different hardware, different ways they use devices, and different expectations.

**Comment by rxhanson** [comment] 2018-12-03 14:10
I forgot to mention that this is in [v1.8.3](https://multitouch.app/versions).

**Comment by lorenzofanchi** [comment] 2018-12-05 12:56
@rxhanson The new implementation seems to work quite well! I would personally change the wording in the preferences though: "difficulty" is not a word a user likes to read in the prefs IMO ;)

"Sensitivity" would fit better, I think. The segmented button options could then be: "Low - Medium - High". This also fits better with the other single word descriptions like "Application" and "Gestures"

**Comment by rxhanson** [comment] 2018-12-06 10:48
@lorenzofanchi Awesome, thanks for giving it a try. Good point on the wording - I'll switch that up for the next release.

**Comment by rxhanson** [comment] 2019-05-21 13:30
Alright, finally had a chance to loop back around to this one. I've just added a beta (v1.11.1) to [the versions page](https://multitouch.app/versions) that includes the first cut at "rest one swipe two" gestures. These gestures do conflict with the built in macOS three finger swipe up or down for Mission Control / Exposé, so you'll want to disable those (or switch them to four finger). If anyone gets a chance to test it out, please let me know!

**Comment by rxhanson** [comment] 2019-06-06 13:11
Gonna go ahead and close this one out, since both rest one swipe one and rest one swipe two are now officially released. If there are any issues with these gestures, feel free to open a new issue.

**Closed by rxhanson** 2019-06-06 13:11 UTC
Labels: feature
